# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180319_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='category',
        ),
    ]
