# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('operation', '0002_auto_20180513_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
