# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180513_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
