# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_coursecomments_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operation.CourseComments'),
        ),
    ]
