# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180516_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomments',
            old_name='comments',
            new_name='text',
        ),
    ]
