# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20180516_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomments',
            old_name='user',
            new_name='user_name',
        ),
    ]
