# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20180516_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='reply_to',
        ),
    ]
