# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0012_remove_coursecomments_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
