# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u8bf4'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0'),
        ),
    ]
