# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180430_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='you_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
